#!/bin/bash

# Set the desired game mode display --- e.g. DP-1 or HDMI-A-1
GAME_MODE_DISPLAY="HDMI-A-1"

# Path to the original script
ORIGINAL_SCRIPT="/usr/lib/steamos/gamescope-session"

# Load the original script through, adding GAME_MODE_DISPLAY at the front of display list to prioritise it
# If the output isn't found then pass the original script through unaltered
if ls /sys/class/drm/card*-"$GAME_MODE_DISPLAY" >/dev/null 2>&1; then
    # The output exists on the GPU. Dynamically inject it into the gamescope command.
    source <(sed "s/-O '\*',eDP-1/-O ${GAME_MODE_DISPLAY},'\*',eDP-1/" "$ORIGINAL_SCRIPT")
else
    # The output does not exist. Fall back to the unmodified original script.
    source "$ORIGINAL_SCRIPT"
fi
